apiVersion: v1
kind: PersistentVolume
metadata:
  name: mystorage
  labels: 
    app: pv-storage

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mystorage
  hostPath: 
    path: /mnt/data
