apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd-metadata-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: nginx-ns  # Use the correct namespace for Fluentd
roleRef:
  kind: ClusterRole
  name: fluentd-metadata-reader
  apiGroup: rbac.authorization.k8s.io
