apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Give it a descriptive name
  name: fluentd-metadata-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
