apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mysql-daemonset
  namespace: nginx-ns
  labels:
    app: mysql

spec:
  selector:
    matchLabels:
      app: mysql
      
  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 80